# Generated by Django 4.1.2 on 2022-12-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('other', 'その他')], default=200, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(default=200),
            preserve_default=False,
        ),
    ]
