# Generated by Django 4.1.2 on 2022-11-11 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ddiary',
            new_name='Diary',
        ),
    ]
