# Generated by Django 4.1.2 on 2022-12-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('llife', '生活'), ('business', 'ビジネス'), ('other', 'その他')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
