# Generated by Django 4.1.2 on 2022-12-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_category_book_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
    ]
