# Generated by Django 4.1.2 on 2022-12-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('life', '生活'), ('business', 'ビジネス'), ('other', 'その他')], max_length=100),
        ),
    ]
